// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/persona.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Grpc.Message {
  public static partial class PersonaService
  {
    static readonly string __ServiceName = "UserInfo.PersonaService";

    static readonly grpc::Marshaller<global::Grpc.Message.UserInfo> __Marshaller_UserInfo_UserInfo = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.Message.UserInfo.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Grpc.Message.UserList> __Marshaller_UserInfo_UserList = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.Message.UserList.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Grpc.Message.UserMsg> __Marshaller_UserInfo_UserMsg = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.Message.UserMsg.Parser.ParseFrom);

    static readonly grpc::Method<global::Grpc.Message.UserInfo, global::Grpc.Message.UserInfo> __Method_Query = new grpc::Method<global::Grpc.Message.UserInfo, global::Grpc.Message.UserInfo>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Query",
        __Marshaller_UserInfo_UserInfo,
        __Marshaller_UserInfo_UserInfo);

    static readonly grpc::Method<global::Grpc.Message.UserInfo, global::Grpc.Message.UserList> __Method_QueryList = new grpc::Method<global::Grpc.Message.UserInfo, global::Grpc.Message.UserList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "QueryList",
        __Marshaller_UserInfo_UserInfo,
        __Marshaller_UserInfo_UserList);

    static readonly grpc::Method<global::Grpc.Message.UserInfo, global::Grpc.Message.UserMsg> __Method_SayHi = new grpc::Method<global::Grpc.Message.UserInfo, global::Grpc.Message.UserMsg>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SayHi",
        __Marshaller_UserInfo_UserInfo,
        __Marshaller_UserInfo_UserMsg);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Grpc.Message.PersonaReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PersonaService</summary>
    [grpc::BindServiceMethod(typeof(PersonaService), "BindService")]
    public abstract partial class PersonaServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Grpc.Message.UserInfo> Query(global::Grpc.Message.UserInfo request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Grpc.Message.UserList> QueryList(global::Grpc.Message.UserInfo request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Grpc.Message.UserMsg> SayHi(global::Grpc.Message.UserInfo request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PersonaService</summary>
    public partial class PersonaServiceClient : grpc::ClientBase<PersonaServiceClient>
    {
      /// <summary>Creates a new client for PersonaService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PersonaServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PersonaService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PersonaServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PersonaServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PersonaServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Grpc.Message.UserInfo Query(global::Grpc.Message.UserInfo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Query(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Grpc.Message.UserInfo Query(global::Grpc.Message.UserInfo request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Query, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Grpc.Message.UserInfo> QueryAsync(global::Grpc.Message.UserInfo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Grpc.Message.UserInfo> QueryAsync(global::Grpc.Message.UserInfo request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Query, null, options, request);
      }
      public virtual global::Grpc.Message.UserList QueryList(global::Grpc.Message.UserInfo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryList(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Grpc.Message.UserList QueryList(global::Grpc.Message.UserInfo request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_QueryList, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Grpc.Message.UserList> QueryListAsync(global::Grpc.Message.UserInfo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryListAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Grpc.Message.UserList> QueryListAsync(global::Grpc.Message.UserInfo request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_QueryList, null, options, request);
      }
      public virtual global::Grpc.Message.UserMsg SayHi(global::Grpc.Message.UserInfo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHi(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Grpc.Message.UserMsg SayHi(global::Grpc.Message.UserInfo request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SayHi, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Grpc.Message.UserMsg> SayHiAsync(global::Grpc.Message.UserInfo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHiAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Grpc.Message.UserMsg> SayHiAsync(global::Grpc.Message.UserInfo request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SayHi, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PersonaServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PersonaServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PersonaServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Query, serviceImpl.Query)
          .AddMethod(__Method_QueryList, serviceImpl.QueryList)
          .AddMethod(__Method_SayHi, serviceImpl.SayHi).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PersonaServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Query, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Grpc.Message.UserInfo, global::Grpc.Message.UserInfo>(serviceImpl.Query));
      serviceBinder.AddMethod(__Method_QueryList, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Grpc.Message.UserInfo, global::Grpc.Message.UserList>(serviceImpl.QueryList));
      serviceBinder.AddMethod(__Method_SayHi, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Grpc.Message.UserInfo, global::Grpc.Message.UserMsg>(serviceImpl.SayHi));
    }

  }
}
#endregion
